# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b97a536de7ffe18b680d62c71b620b71bb0350c55ec2908baee435f94b8a3b862699412a94a58ff8e3c189427deab52edf53ad9280c675e4a5262e87e68b2f0f

test:
  secret_key_base: 796b7c4911e08d51ff7371478e07406c867fa0d2ec7a83cfcfe0161d9586fa38d7c8ca80fdd7ea805aaf5c504ef7fe2409e358fd6bf583c7cb45ca9cff75d78f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
